version: "3"

services:
  api:
    image: nlodato6/paddle-nav-api:1.0.6
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/paddle_nav_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=paddle_nav_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SETTINGS_MODULE=paddle_nav_proj.settings
    expose:
      - "8000"

  nginx:
    image: nlodato6/paddle-nav-web:1.0.6
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api

  db:
    image: imresamu/postgis:16-3.5-bullseye
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h http://3.15.164.141"]
      interval: 3s
      timeout: 5s
      retries: 20
      start_period: 5s
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=paddle_nav_db
    volumes: 
      - postgres_data:/var/lib/postgresql/data
      - 

volumes:
  postgres_data:
