services:
  # api:
  #   build: .
  #   depends_on:
  #     - db
  # nginx:
  #   build: 
  #     context: .
  #     dockerfile: ./webserver/Dockerfile
  #   restart: always
  #   ports:
  #     - "80:80"
  db:
    image: imresamu/postgis:16-3.5-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=paddle_nav_db
    ports:
      - '5454:5432'
    volumes: 
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: