# Generated by Django 5.2.4 on 2025-09-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recreationarea',
            name='county',
            field=models.CharField(default='n/a', max_length=100),
        ),
    ]
