# Generated by Django 5.2.4 on 2025-09-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0002_alter_recreationarea_county'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recreationarea',
            name='county',
        ),
    ]
