# Generated by Django 5.2.4 on 2025-09-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0003_remove_recreationarea_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='recreationarea',
            name='county',
            field=models.CharField(default='n/a', max_length=100),
        ),
    ]
