# Generated by Django 5.2.4 on 2025-09-03 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0003_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recreationarea',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_location', to='locations_app.recreationarea'),
        ),
    ]
