# Generated by Django 5.2.4 on 2025-09-04 23:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0004_recreationarea_favorited_by_alter_favorite_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recreationarea',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
