# Generated by Django 5.2.4 on 2025-09-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0005_alter_recreationarea_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='recreationarea',
            name='api_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
