# Generated by Django 5.2.4 on 2025-09-05 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0006_recreationarea_api_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recreationarea',
            old_name='api_id',
            new_name='OBJECTID',
        ),
    ]
