# Generated by Django 5.2.4 on 2025-09-05 02:21

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0007_rename_api_id_recreationarea_objectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recreationarea',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
