# Generated by Django 5.2.4 on 2025-09-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations_app', '0008_alter_recreationarea_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recreationarea',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='recreationarea',
            name='city',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
